// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CreateIssue
  static let CreateIssuePayload = Object(
    typename: "CreateIssuePayload",
    implementedInterfaces: []
  )
}